language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
 # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install enum34;
    fi
  - conda install coverage
  - conda install numpy
  - conda install scipy
  - conda install pandas
  - conda install toolz
  - conda install cython
  - pip install --upgrade pip
  - pip install IPython
  - pip install logbook
  - pip install python-decouple
  - pip install mock
  - pip install argcheck
  - pip install --use-wheel finance-python
  - pip install coveralls
# command to run tests
script:
  - coverage run WindAdapter/tests/test_suite.py
after_success:
  - coveralls
