language: python
python:
  - "2.6"
  - "2.7"
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install WindAdapter
  
# command to run tests
script:
  - coverage run --source=WindAdapter setup.py test
after_success:
  - coveralls
