language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - python setup.py install
  - pip install coveralls
  - pip install mock
  - pip install enum
# command to run tests
script:
  - coverage run WindAdapter/test/test_api.py
after_success:
  - coveralls
